### ISSUE TITLE
FairParRootFileIo might cause problems in executables

### ISSUE THREAD

**Issue by miharenthas** [FairRootGroup/FairRoot#720]
Here's the annoying guy who compiles program instead of using scripts again.

In the above mentioned hierarchy (there's absolutely no guarantee that the actual FairParRootFileIo class is to blame) there might be a double-free that causes a segfault on exit. In a compiled program.

[malloc-screwup.txt](https://github.com/FairRootGroup/FairRoot/files/1678233/malloc-screwup.txt)

From a cursory reading of FariParRootFileIo and its parent FairParIo, it looks like the variable FairParIo::detFarIoList is deallocated in two places. The first one is in FairParRootFileIo::close():

```
void FairParRootFileIo::close()
{
  // closes an open ROOT file and deletes the detector I/Os
  if (file) {
    file->Close();
    delete file;
    file=0;
  }
  if (detParIoList) {
    detParIoList->Delete();
  }
}
```

The second one is in the destructor of FairParIo:
```
FairParIo::~FairParIo()
{
  // default destructor
  if(detParIoList) {
    detParIoList->Delete();
    delete detParIoList;
    detParIoList=0;
  }
}
```

The check for NULL might not work, and detParIoList could be deleted twice (or actually the Delete() method might be called on an invalid object, leading to a segfault) --in the very verbose file attached above TList does appear; that, and the non-segfaulty behavior of the program when I omit to use the parameter file suggests that these should be good places to begin looking at the problem.

My current solution is: don't use the parameter file. I never actually needed and by working around issue #705 I essentially don't miss it. Still, it's not nice to have a program segfaulting itself to death at exit...

**Comment by MohammadAlTurany** [comment]
Did you try it with the dev from this week?  We merged a PR from Rubin (PR #719 ) which could be very related to this issue.

**Comment by miharenthas** [comment]
That particular commit solves a problem that became apparent with root 6.12 (Fedora 27 updated today). It certainly seems related, but applying the commit doesn't solve the problem I wrote about above.

Thanks for the suggestion anyway!

**Comment by MohammadAlTurany** [comment]
Hi,

TList is used in many places and not only here! Where you see the connection to the method above? 
The ROOT output you send does not show any thing related to FairParIo, it only tells that it is in the List::Delete(), could you please run with the debugger? or tell me how to reproduce this problem. In AliceO2 we do not use also any macros any more and we do not see this problem.

best,
Mohammad

**Comment by miharenthas** [comment]
Hi,
Well, the connection is that if I don't use FairParBaseRootFileIo my program doesn't break on exit... since I have a workaround, I didn't really investigate much.
I'll post some debugger output in a while, maybe... but don't loose any sleep over this

Best,
L.
